[build]
  command = "pip install -r requirements.txt" # 安装依赖
  publish = "." # 发布目录，可以设为当前目录或留空

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app" # 将所有请求定向到我们创建的函数
  status = 200

[functions]
  directory = "functions" # 指定函数代码所在目录